services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: barkasse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_log:/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    container_name: barkasse-nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nodered_data:/data
      - ./ui:/data/ui
    depends_on:
      - mosquitto
